/*
 * generated by Xtext 2.20.0
 */
package org.reaction.dsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.reaction.dsl.parser.antlr.internal.InternalReactionLanguageParser;
import org.reaction.dsl.services.ReactionLanguageGrammarAccess;

public class ReactionLanguageParser extends AbstractAntlrParser {

	@Inject
	private ReactionLanguageGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalReactionLanguageParser createParser(XtextTokenStream stream) {
		return new InternalReactionLanguageParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ReactionModel";
	}

	public ReactionLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ReactionLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
