/**
 * generated by Xtext 2.20.0
 */
package org.reaction.dsl.ide;

import org.reaction.dsl.ide.AbstractReactionLanguageIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ReactionLanguageIdeModule extends AbstractReactionLanguageIdeModule {
}
