<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="GKLModel" nsURI="platform:/resource/org.reaction.gklExample/model/GKL.ecore"
    nsPrefix="GKLModel">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel"/>
  <eClassifiers xsi:type="ecore:EClass" name="P" eSuperTypes="platform:/resource/org.reaction.reactionmodel/model/ReactionModel.ecore#//Agent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="P_a_T_x" eType="ecore:EClass platform:/resource/org.reaction.gklExample/model/GKL.ecore#//T"
        eOpposite="platform:/resource/org.reaction.gklExample/model/GKL.ecore#//T/T_x_P_a"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="P_a_T_y" eType="ecore:EClass platform:/resource/org.reaction.gklExample/model/GKL.ecore#//T"
        eOpposite="platform:/resource/org.reaction.gklExample/model/GKL.ecore#//T/T_y_P_a"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="T" eSuperTypes="platform:/resource/org.reaction.reactionmodel/model/ReactionModel.ecore#//Agent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="T_x_P_a" eType="ecore:EClass platform:/resource/org.reaction.gklExample/model/GKL.ecore#//P"
        eOpposite="platform:/resource/org.reaction.gklExample/model/GKL.ecore#//P/P_a_T_x"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="T_y_P_a" eType="ecore:EClass platform:/resource/org.reaction.gklExample/model/GKL.ecore#//P"
        eOpposite="platform:/resource/org.reaction.gklExample/model/GKL.ecore#//P/P_a_T_y"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="T_x_K_a" eType="ecore:EClass platform:/resource/org.reaction.gklExample/model/GKL.ecore#//K"
        eOpposite="platform:/resource/org.reaction.gklExample/model/GKL.ecore#//K/K_a_T_x"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="T_x_u" eType="ecore:EClass platform:/resource/org.reaction.gklExample/model/GKL.ecore#//U_s"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="T_x_p" eType="ecore:EClass platform:/resource/org.reaction.gklExample/model/GKL.ecore#//P_s"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="T_y_K_a" eType="ecore:EClass platform:/resource/org.reaction.gklExample/model/GKL.ecore#//K"
        eOpposite="platform:/resource/org.reaction.gklExample/model/GKL.ecore#//K/K_a_T_y"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="T_y_u" eType="ecore:EClass platform:/resource/org.reaction.gklExample/model/GKL.ecore#//U_s"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="T_y_p" eType="ecore:EClass platform:/resource/org.reaction.gklExample/model/GKL.ecore#//P_s"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="K" eSuperTypes="platform:/resource/org.reaction.reactionmodel/model/ReactionModel.ecore#//Agent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="K_a_T_x" eType="ecore:EClass platform:/resource/org.reaction.gklExample/model/GKL.ecore#//T"
        eOpposite="platform:/resource/org.reaction.gklExample/model/GKL.ecore#//T/T_x_K_a"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="K_a_T_y" eType="ecore:EClass platform:/resource/org.reaction.gklExample/model/GKL.ecore#//T"
        eOpposite="platform:/resource/org.reaction.gklExample/model/GKL.ecore#//T/T_y_K_a"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="U_s" eSuperTypes="platform:/resource/org.reaction.reactionmodel/model/ReactionModel.ecore#//State"/>
  <eClassifiers xsi:type="ecore:EClass" name="P_s" eSuperTypes="platform:/resource/org.reaction.reactionmodel/model/ReactionModel.ecore#//State"/>
</ecore:EPackage>
