<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xsi:schemaLocation="http://www.eclipse.org/emf/2002/Ecore java://org.eclipse.emf.ecore.EcorePackage"
    name="GKLModel" nsURI="platform:/resource/org.reaction.gklExample/model/GKLModel.ecore"
    nsPrefix="GKLModel">
  <eClassifiers xmi:type="ecore:EClass" name="P" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="P_a_T_x" eType="#//T" eOpposite="#//T/T_x_P_a"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="P_a_T_y" eType="#//T" eOpposite="#//T/T_y_P_a"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="T" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="T_x_P_a" eType="#//P" eOpposite="#//P/P_a_T_x"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="T_y_P_a" eType="#//P" eOpposite="#//P/P_a_T_y"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="T_x_K_a" eType="#//K" eOpposite="#//K/K_a_T_x"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="T_x_u" eType="#//U_s"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="T_x_p" eType="#//P_s"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="T_y_K_a" eType="#//K" eOpposite="#//K/K_a_T_y"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="T_y_u" eType="#//U_s"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="T_y_p" eType="#//P_s"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="K" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="K_a_T_x" eType="#//T" eOpposite="#//T/T_x_K_a"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="K_a_T_y" eType="#//T" eOpposite="#//T/T_y_K_a"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="U_s" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="P_s" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//State"/>
</ecore:EPackage>
