/**
 *
 * $Id$
 */
package TestcasesModel.validation;

import TestcasesModel.A;
import TestcasesModel.P_s;
import TestcasesModel.U_s;
import TestcasesModel.X;

/**
 * A sample validator interface for {@link TestcasesModel.A}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AValidator {
	boolean validate();

	boolean validateA_b_X_z(X value);

	boolean validateA_b_A_c(A value);

	boolean validateA_b_A_b(A value);

	boolean validateA_c_X_z(X value);

	boolean validateA_c_X_y(X value);

	boolean validateA_c_u(U_s value);

	boolean validateA_c_p(P_s value);
}
