/**
 *
 * $Id$
 */
package TestcasesModel.validation;

import reactionContainer.Agent;

/**
 * A sample validator interface for {@link TestcasesModel.T}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TValidator {
	boolean validate();

	boolean validateT_i(Agent value);

	boolean validateT_j(Agent value);
}
