/**
 * generated by Xtext 2.20.0
 */
package org.reaction.dsl.reactionLanguage.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.reaction.dsl.reactionLanguage.ArithmeticExpr;
import org.reaction.dsl.reactionLanguage.ReactionLanguagePackage;
import org.reaction.dsl.reactionLanguage.TerminateIterations;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Terminate Iterations</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.reaction.dsl.reactionLanguage.impl.TerminateIterationsImpl#getIterations <em>Iterations</em>}</li>
 * </ul>
 *
 * @generated
 */
public class TerminateIterationsImpl extends TerminateBodyImpl implements TerminateIterations
{
  /**
   * The cached value of the '{@link #getIterations() <em>Iterations</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIterations()
   * @generated
   * @ordered
   */
  protected ArithmeticExpr iterations;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TerminateIterationsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ReactionLanguagePackage.Literals.TERMINATE_ITERATIONS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ArithmeticExpr getIterations()
  {
    return iterations;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetIterations(ArithmeticExpr newIterations, NotificationChain msgs)
  {
    ArithmeticExpr oldIterations = iterations;
    iterations = newIterations;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ReactionLanguagePackage.TERMINATE_ITERATIONS__ITERATIONS, oldIterations, newIterations);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIterations(ArithmeticExpr newIterations)
  {
    if (newIterations != iterations)
    {
      NotificationChain msgs = null;
      if (iterations != null)
        msgs = ((InternalEObject)iterations).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ReactionLanguagePackage.TERMINATE_ITERATIONS__ITERATIONS, null, msgs);
      if (newIterations != null)
        msgs = ((InternalEObject)newIterations).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ReactionLanguagePackage.TERMINATE_ITERATIONS__ITERATIONS, null, msgs);
      msgs = basicSetIterations(newIterations, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ReactionLanguagePackage.TERMINATE_ITERATIONS__ITERATIONS, newIterations, newIterations));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ReactionLanguagePackage.TERMINATE_ITERATIONS__ITERATIONS:
        return basicSetIterations(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ReactionLanguagePackage.TERMINATE_ITERATIONS__ITERATIONS:
        return getIterations();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ReactionLanguagePackage.TERMINATE_ITERATIONS__ITERATIONS:
        setIterations((ArithmeticExpr)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ReactionLanguagePackage.TERMINATE_ITERATIONS__ITERATIONS:
        setIterations((ArithmeticExpr)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ReactionLanguagePackage.TERMINATE_ITERATIONS__ITERATIONS:
        return iterations != null;
    }
    return super.eIsSet(featureID);
  }

} //TerminateIterationsImpl
