/**
 * generated by Xtext 2.20.0
 */
package org.reaction.dsl.reactionLanguage.impl;

import org.eclipse.emf.ecore.EClass;

import org.reaction.dsl.reactionLanguage.ReactionLanguagePackage;
import org.reaction.dsl.reactionLanguage.TerminateBody;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Terminate Body</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TerminateBodyImpl extends TerminateCommandImpl implements TerminateBody
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TerminateBodyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ReactionLanguagePackage.Literals.TERMINATE_BODY;
  }

} //TerminateBodyImpl
