/*
 * generated by Xtext 2.20.0
 */
package org.reaction.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ReactionLanguageRuntimeModule extends AbstractReactionLanguageRuntimeModule {
}
