/*
 * generated by Xtext 2.20.0
 */
package org.reaction.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractReactionLanguageScopeProvider extends DelegatingScopeProvider {
}
