/**
 *
 * $Id$
 */
package ecoreBCModel.validation;

import ecoreBCModel.CommandType;
import ecoreBCModel.IntermPattern;

/**
 * A sample validator interface for {@link ecoreBCModel.IntermCommand}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IntermCommandValidator {
	boolean validate();

	boolean validateType(CommandType value);

	boolean validatePatternToMatch(IntermPattern value);

	boolean validateCnt(double value);
}
