/**
 *
 * $Id$
 */
package ecoreBCModel.validation;

import ecoreBCModel.BindingState;
import ecoreBCModel.IntermAgentInstance;
import ecoreBCModel.IntermSite;
import ecoreBCModel.IntermSiteInstance;
import ecoreBCModel.IntermSiteState;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ecoreBCModel.IntermSiteInstance}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IntermSiteInstanceValidator {
	boolean validate();

	boolean validateInstanceOf(IntermSite value);

	boolean validateNotBoundTo(EList<IntermSiteInstance> value);

	boolean validateBoundTo(IntermSiteInstance value);

	boolean validateBindingState(BindingState value);

	boolean validateName(String value);

	boolean validateState(IntermSiteState value);

	boolean validateParent(IntermAgentInstance value);
}
