/**
 * generated by Xtext 2.20.0
 */
package org.reaction.dsl;

import org.reaction.dsl.AbstractReactionLanguageRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ReactionLanguageRuntimeModule extends AbstractReactionLanguageRuntimeModule {
}
