/**
 * generated by Xtext 2.20.0
 */
package org.reaction.dsl.ui.contentassist;

import org.reaction.dsl.ui.contentassist.AbstractReactionLanguageProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ReactionLanguageProposalProvider extends AbstractReactionLanguageProposalProvider {
}
