/*
 * generated by Xtext 2.20.0
 */
package org.reaction.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;
import org.eclipse.xtext.validation.ComposedChecks;

@ComposedChecks(validators = {ReactionLanguageNamesAreUniqueValidator.class})
public abstract class AbstractReactionLanguageValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.reaction.dsl.reactionLanguage.ReactionLanguagePackage.eINSTANCE);
		return result;
	}
}
