/**
 * generated by Xtext 2.20.0
 */
package org.reaction.dsl.reactionLanguage;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bonds</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.reaction.dsl.reactionLanguage.Bonds#getBonds <em>Bonds</em>}</li>
 * </ul>
 *
 * @see org.reaction.dsl.reactionLanguage.ReactionLanguagePackage#getBonds()
 * @model
 * @generated
 */
public interface Bonds extends Pattern
{
  /**
   * Returns the value of the '<em><b>Bonds</b></em>' containment reference list.
   * The list contents are of type {@link org.reaction.dsl.reactionLanguage.Bond}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bonds</em>' containment reference list.
   * @see org.reaction.dsl.reactionLanguage.ReactionLanguagePackage#getBonds_Bonds()
   * @model containment="true"
   * @generated
   */
  EList<Bond> getBonds();

} // Bonds
