/**
 * generated by Xtext 2.20.0
 */
package org.reaction.dsl.reactionLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bond Side Or Wildcard</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.reaction.dsl.reactionLanguage.BondSideOrWildcard#getWildcard <em>Wildcard</em>}</li>
 * </ul>
 *
 * @see org.reaction.dsl.reactionLanguage.ReactionLanguagePackage#getBondSideOrWildcard()
 * @model
 * @generated
 */
public interface BondSideOrWildcard extends EObject
{
  /**
   * Returns the value of the '<em><b>Wildcard</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Wildcard</em>' containment reference.
   * @see #setWildcard(Wildcard)
   * @see org.reaction.dsl.reactionLanguage.ReactionLanguagePackage#getBondSideOrWildcard_Wildcard()
   * @model containment="true"
   * @generated
   */
  Wildcard getWildcard();

  /**
   * Sets the value of the '{@link org.reaction.dsl.reactionLanguage.BondSideOrWildcard#getWildcard <em>Wildcard</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Wildcard</em>' containment reference.
   * @see #getWildcard()
   * @generated
   */
  void setWildcard(Wildcard value);

} // BondSideOrWildcard
