/**
 * generated by Xtext 2.20.0
 */
package org.reaction.dsl.reactionLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Command</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.reaction.dsl.reactionLanguage.ReactionLanguagePackage#getCommand()
 * @model
 * @generated
 */
public interface Command extends Component
{
} // Command
