/**
 * generated by Xtext 2.20.0
 */
package org.reaction.dsl.reactionLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Component</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.reaction.dsl.reactionLanguage.ReactionLanguagePackage#getComponent()
 * @model
 * @generated
 */
public interface Component extends EObject
{
} // Component
