/**
 * generated by Xtext 2.20.0
 */
package org.reaction.dsl.reactionLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.reaction.dsl.reactionLanguage.FunctionCall#getFunc <em>Func</em>}</li>
 *   <li>{@link org.reaction.dsl.reactionLanguage.FunctionCall#getExpr <em>Expr</em>}</li>
 * </ul>
 *
 * @see org.reaction.dsl.reactionLanguage.ReactionLanguagePackage#getFunctionCall()
 * @model
 * @generated
 */
public interface FunctionCall extends ArithmeticExpr
{
  /**
   * Returns the value of the '<em><b>Func</b></em>' attribute.
   * The literals are from the enumeration {@link org.reaction.dsl.reactionLanguage.MathFunc}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Func</em>' attribute.
   * @see org.reaction.dsl.reactionLanguage.MathFunc
   * @see #setFunc(MathFunc)
   * @see org.reaction.dsl.reactionLanguage.ReactionLanguagePackage#getFunctionCall_Func()
   * @model
   * @generated
   */
  MathFunc getFunc();

  /**
   * Sets the value of the '{@link org.reaction.dsl.reactionLanguage.FunctionCall#getFunc <em>Func</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Func</em>' attribute.
   * @see org.reaction.dsl.reactionLanguage.MathFunc
   * @see #getFunc()
   * @generated
   */
  void setFunc(MathFunc value);

  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(ArithmeticExpr)
   * @see org.reaction.dsl.reactionLanguage.ReactionLanguagePackage#getFunctionCall_Expr()
   * @model containment="true"
   * @generated
   */
  ArithmeticExpr getExpr();

  /**
   * Sets the value of the '{@link org.reaction.dsl.reactionLanguage.FunctionCall#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(ArithmeticExpr value);

} // FunctionCall
