/**
 * generated by Xtext 2.20.0
 */
package org.reaction.dsl.reactionLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Initialisation Head</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.reaction.dsl.reactionLanguage.InitialisationHead#getCnt <em>Cnt</em>}</li>
 * </ul>
 *
 * @see org.reaction.dsl.reactionLanguage.ReactionLanguagePackage#getInitialisationHead()
 * @model
 * @generated
 */
public interface InitialisationHead extends EObject
{
  /**
   * Returns the value of the '<em><b>Cnt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cnt</em>' containment reference.
   * @see #setCnt(ArithmeticExpr)
   * @see org.reaction.dsl.reactionLanguage.ReactionLanguagePackage#getInitialisationHead_Cnt()
   * @model containment="true"
   * @generated
   */
  ArithmeticExpr getCnt();

  /**
   * Sets the value of the '{@link org.reaction.dsl.reactionLanguage.InitialisationHead#getCnt <em>Cnt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cnt</em>' containment reference.
   * @see #getCnt()
   * @generated
   */
  void setCnt(ArithmeticExpr value);

} // InitialisationHead
