/**
 * generated by Xtext 2.20.0
 */
package org.reaction.dsl.reactionLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Observable Arithmetic</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.reaction.dsl.reactionLanguage.ObservableArithmetic#getExpr <em>Expr</em>}</li>
 * </ul>
 *
 * @see org.reaction.dsl.reactionLanguage.ReactionLanguagePackage#getObservableArithmetic()
 * @model
 * @generated
 */
public interface ObservableArithmetic extends EObject
{
  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(ArithmeticExpr)
   * @see org.reaction.dsl.reactionLanguage.ReactionLanguagePackage#getObservableArithmetic_Expr()
   * @model containment="true"
   * @generated
   */
  ArithmeticExpr getExpr();

  /**
   * Sets the value of the '{@link org.reaction.dsl.reactionLanguage.ObservableArithmetic#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(ArithmeticExpr value);

} // ObservableArithmetic
