/**
 * generated by Xtext 2.20.0
 */
package org.reaction.dsl.reactionLanguage;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.reaction.dsl.reactionLanguage.ReactionLanguagePackage
 * @generated
 */
public interface ReactionLanguageFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ReactionLanguageFactory eINSTANCE = org.reaction.dsl.reactionLanguage.impl.ReactionLanguageFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Reaction Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Reaction Model</em>'.
   * @generated
   */
  ReactionModel createReactionModel();

  /**
   * Returns a new object of class '<em>Component</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Component</em>'.
   * @generated
   */
  Component createComponent();

  /**
   * Returns a new object of class '<em>Agent</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Agent</em>'.
   * @generated
   */
  Agent createAgent();

  /**
   * Returns a new object of class '<em>Agent Declaration</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Agent Declaration</em>'.
   * @generated
   */
  AgentDeclaration createAgentDeclaration();

  /**
   * Returns a new object of class '<em>Agent Instance</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Agent Instance</em>'.
   * @generated
   */
  AgentInstance createAgentInstance();

  /**
   * Returns a new object of class '<em>Site</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Site</em>'.
   * @generated
   */
  Site createSite();

  /**
   * Returns a new object of class '<em>Site State</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Site State</em>'.
   * @generated
   */
  SiteState createSiteState();

  /**
   * Returns a new object of class '<em>Complex</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Complex</em>'.
   * @generated
   */
  Complex createComplex();

  /**
   * Returns a new object of class '<em>Complex Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Complex Element</em>'.
   * @generated
   */
  ComplexElement createComplexElement();

  /**
   * Returns a new object of class '<em>Signature</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Signature</em>'.
   * @generated
   */
  Signature createSignature();

  /**
   * Returns a new object of class '<em>Rule</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rule</em>'.
   * @generated
   */
  Rule createRule();

  /**
   * Returns a new object of class '<em>Rule Head</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rule Head</em>'.
   * @generated
   */
  RuleHead createRuleHead();

  /**
   * Returns a new object of class '<em>Rule Body</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rule Body</em>'.
   * @generated
   */
  RuleBody createRuleBody();

  /**
   * Returns a new object of class '<em>Rates</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rates</em>'.
   * @generated
   */
  Rates createRates();

  /**
   * Returns a new object of class '<em>Pattern</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pattern</em>'.
   * @generated
   */
  Pattern createPattern();

  /**
   * Returns a new object of class '<em>Bonds</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bonds</em>'.
   * @generated
   */
  Bonds createBonds();

  /**
   * Returns a new object of class '<em>Abstract Agent</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Abstract Agent</em>'.
   * @generated
   */
  AbstractAgent createAbstractAgent();

  /**
   * Returns a new object of class '<em>Bond</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bond</em>'.
   * @generated
   */
  Bond createBond();

  /**
   * Returns a new object of class '<em>Bond Side Or Wildcard</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bond Side Or Wildcard</em>'.
   * @generated
   */
  BondSideOrWildcard createBondSideOrWildcard();

  /**
   * Returns a new object of class '<em>Wildcard</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Wildcard</em>'.
   * @generated
   */
  Wildcard createWildcard();

  /**
   * Returns a new object of class '<em>Bond Side</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bond Side</em>'.
   * @generated
   */
  BondSide createBondSide();

  /**
   * Returns a new object of class '<em>Site Instance</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Site Instance</em>'.
   * @generated
   */
  SiteInstance createSiteInstance();

  /**
   * Returns a new object of class '<em>Site Instance State</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Site Instance State</em>'.
   * @generated
   */
  SiteInstanceState createSiteInstanceState();

  /**
   * Returns a new object of class '<em>Variable</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Variable</em>'.
   * @generated
   */
  Variable createVariable();

  /**
   * Returns a new object of class '<em>Initialisation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Initialisation</em>'.
   * @generated
   */
  Initialisation createInitialisation();

  /**
   * Returns a new object of class '<em>Initialisation Head</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Initialisation Head</em>'.
   * @generated
   */
  InitialisationHead createInitialisationHead();

  /**
   * Returns a new object of class '<em>Initialisation Body</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Initialisation Body</em>'.
   * @generated
   */
  InitialisationBody createInitialisationBody();

  /**
   * Returns a new object of class '<em>Observable</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Observable</em>'.
   * @generated
   */
  Observable createObservable();

  /**
   * Returns a new object of class '<em>Observable Body</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Observable Body</em>'.
   * @generated
   */
  ObservableBody createObservableBody();

  /**
   * Returns a new object of class '<em>Observable Arithmetic</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Observable Arithmetic</em>'.
   * @generated
   */
  ObservableArithmetic createObservableArithmetic();

  /**
   * Returns a new object of class '<em>Observable Pattern</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Observable Pattern</em>'.
   * @generated
   */
  ObservablePattern createObservablePattern();

  /**
   * Returns a new object of class '<em>Command</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Command</em>'.
   * @generated
   */
  Command createCommand();

  /**
   * Returns a new object of class '<em>Terminate Command</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Terminate Command</em>'.
   * @generated
   */
  TerminateCommand createTerminateCommand();

  /**
   * Returns a new object of class '<em>Terminate Body</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Terminate Body</em>'.
   * @generated
   */
  TerminateBody createTerminateBody();

  /**
   * Returns a new object of class '<em>Terminate Time</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Terminate Time</em>'.
   * @generated
   */
  TerminateTime createTerminateTime();

  /**
   * Returns a new object of class '<em>Terminate Iterations</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Terminate Iterations</em>'.
   * @generated
   */
  TerminateIterations createTerminateIterations();

  /**
   * Returns a new object of class '<em>Terminate Count</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Terminate Count</em>'.
   * @generated
   */
  TerminateCount createTerminateCount();

  /**
   * Returns a new object of class '<em>Arithmetic Expr</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Arithmetic Expr</em>'.
   * @generated
   */
  ArithmeticExpr createArithmeticExpr();

  /**
   * Returns a new object of class '<em>Blank Pattern</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Blank Pattern</em>'.
   * @generated
   */
  BlankPattern createBlankPattern();

  /**
   * Returns a new object of class '<em>Plus</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Plus</em>'.
   * @generated
   */
  Plus createPlus();

  /**
   * Returns a new object of class '<em>Minus</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Minus</em>'.
   * @generated
   */
  Minus createMinus();

  /**
   * Returns a new object of class '<em>Multi</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Multi</em>'.
   * @generated
   */
  Multi createMulti();

  /**
   * Returns a new object of class '<em>Div</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Div</em>'.
   * @generated
   */
  Div createDiv();

  /**
   * Returns a new object of class '<em>Pow</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pow</em>'.
   * @generated
   */
  Pow createPow();

  /**
   * Returns a new object of class '<em>Number Literal</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Number Literal</em>'.
   * @generated
   */
  NumberLiteral createNumberLiteral();

  /**
   * Returns a new object of class '<em>Function Call</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Function Call</em>'.
   * @generated
   */
  FunctionCall createFunctionCall();

  /**
   * Returns a new object of class '<em>Var Ref</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Var Ref</em>'.
   * @generated
   */
  VarRef createVarRef();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  ReactionLanguagePackage getReactionLanguagePackage();

} //ReactionLanguageFactory
