/**
 * generated by Xtext 2.20.0
 */
package org.reaction.dsl.reactionLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Site Instance</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.reaction.dsl.reactionLanguage.SiteInstance#getSite <em>Site</em>}</li>
 *   <li>{@link org.reaction.dsl.reactionLanguage.SiteInstance#getSiteState <em>Site State</em>}</li>
 * </ul>
 *
 * @see org.reaction.dsl.reactionLanguage.ReactionLanguagePackage#getSiteInstance()
 * @model
 * @generated
 */
public interface SiteInstance extends EObject
{
  /**
   * Returns the value of the '<em><b>Site</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Site</em>' reference.
   * @see #setSite(Site)
   * @see org.reaction.dsl.reactionLanguage.ReactionLanguagePackage#getSiteInstance_Site()
   * @model
   * @generated
   */
  Site getSite();

  /**
   * Sets the value of the '{@link org.reaction.dsl.reactionLanguage.SiteInstance#getSite <em>Site</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Site</em>' reference.
   * @see #getSite()
   * @generated
   */
  void setSite(Site value);

  /**
   * Returns the value of the '<em><b>Site State</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Site State</em>' containment reference.
   * @see #setSiteState(SiteInstanceState)
   * @see org.reaction.dsl.reactionLanguage.ReactionLanguagePackage#getSiteInstance_SiteState()
   * @model containment="true"
   * @generated
   */
  SiteInstanceState getSiteState();

  /**
   * Sets the value of the '{@link org.reaction.dsl.reactionLanguage.SiteInstance#getSiteState <em>Site State</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Site State</em>' containment reference.
   * @see #getSiteState()
   * @generated
   */
  void setSiteState(SiteInstanceState value);

} // SiteInstance
