/**
 * generated by Xtext 2.20.0
 */
package org.reaction.dsl.reactionLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Terminate Body</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.reaction.dsl.reactionLanguage.ReactionLanguagePackage#getTerminateBody()
 * @model
 * @generated
 */
public interface TerminateBody extends TerminateCommand
{
} // TerminateBody
