/**
 * generated by Xtext 2.20.0
 */
package org.reaction.dsl.reactionLanguage;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Terminate Command</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.reaction.dsl.reactionLanguage.ReactionLanguagePackage#getTerminateCommand()
 * @model
 * @generated
 */
public interface TerminateCommand extends Command
{
} // TerminateCommand
